services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/movies
    ports:
      - "7000:7000"
