version: '3.8'
services:
  api:
    build: .
    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: